# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-03 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
