# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181003_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва іспиту')),
                ('date', models.DateTimeField(verbose_name='Дата іспиту')),
                ('teacher', models.CharField(max_length=256, verbose_name='Викладач')),
                ('exam_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Group', verbose_name='Група')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Іспити',
                'verbose_name': 'Іспит',
            },
        ),
    ]
